apiVersion: v1
kind: Pod
metadata:
  name: flower-app
  namespace: asad-ns
  labels:
    app: flower-app
spec:
  containers:
    - name: flower-app-container
      image: asadoblivion/flower-app:v2
      ports:
        - conatinerPort: 3000
