apiVersion: v1
kind: Pod
metadata:
  name: flower-app
  namespace: asad-ns
  lables:
    app: flower-app
spec:
  containers:
    - name: flower-app-container
      image: asadoblivion/flower-app:tagname
      ports:
        - conatinerPort: 3000
